[package]
name = "top-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.10"
thread-priority = "0.15"

ratatui = "0.24.0"
crossterm = "0.27.0"
pretty-bytes = "0.2.2"

rayon = "1.8.0"
